### ISSUE TITLE
Problem with opening a file

### ISSUE THREAD

**Issue by midraft** [goribby/Cyberpunk2077-MultiRig#1]
I hope I understood correctly that here you can write problems that have arisen, I do not open the project in blender, I start and the program crashes without starting the project

**Comment by goribby** [comment]
> I hope I understood correctly that here you can write problems that have arisen

Absolutely! That's exactly what this is for.

I'll need some more info to help you solve this:

1. What are your PC specifications? (e.g. GPU, CPU, RAM, Operating System, Blender Version, etc.)
2. Go to the folder where Blender is installed, and open "blender_debug_log.cmd"
3. Open the rig .blend so it crashes
4. Attach both blender_debug_output.txt and blender_system_info.txt (it should open the debug_logs folder automatically when the app closes or crashes)

That will help me understand what's going on and how to fix it.
